### ISSUE TITLE
An unrelated question

### ISSUE THREAD

**Issue by spalemg** [shelvacu/test-github-race#2]
Hello, I saw your post on Android Stack Exchange (http://android.stackexchange.com/questions/117337/how-to-map-hard-key-combinations-to-keys-in-motorola-photon-q-xt897) and have the same very problem. Unfortunately neither Stack Exchange nor Github allow direct user-to-user messaging so this is the only recourse I had. 
Were you able to find a solution to your question? 
Thanks!
Spalem

**Comment by shelvacu** [comment]
Oh, I'd forgotten about that question. I got a little farther, but never actually got it to work and I could never figure out why, which is why I never answered it. I've given as much as I know as an answer:

http://android.stackexchange.com/a/143939/119794

if you are unable to comment on that post then you can also email me shelvacu@gmail.com
